fixtures:
  repositories:
    dirtree: "git://github.com/puppetlabs/pltraining-dirtree.git"
    dockeragent: "git://github.com/puppetlabs/pltraining-dockeragent.git"
    rbac: "git://github.com/puppetlabs/pltraining-rbac.git"
    userprefs: "git://github.com/puppetlabs/pltraining-userprefs.git"
    pe_repo: "git@github.com:puppetlabs/puppetlabs-pe_repo.git"
    pe_accounts: "git@github.com:puppetlabs/puppetlabs-pe_accounts.git"
    pe_concat: "git@github.com:puppetlabs/puppetlabs-pe_concat.git"
    pe_console_prune: "git@github.com:puppetlabs/puppetlabs-pe_console_prune.git"
    pe_hocon: "git@github.com:puppetlabs/puppetlabs-pe_hocon.git"
    pe_inifile:
      repo: "git@github.com:puppetlabs/puppetlabs-pe_inifile.git"
      branch: "2016.2.x"
    pe_java_ks: "git@github.com:puppetlabs/puppetlabs-pe_java_ks.git"
    pe_nginx: "git@github.com:puppetlabs/puppetlabs-pe_nginx.git"
    pe_postgresql: "git@github.com:puppetlabs/puppetlabs-pe_postgresql.git"
    pe_puppet_authorization: "git@github.com:puppetlabs/puppetlabs-pe_puppet_authorization.git"
    pe_puppetdbquery: "git@github.com:puppetlabs/puppetlabs-pe_puppetdbquery.git"
    pe_r10k: "git@github.com:puppetlabs/puppetlabs-pe_r10k.git"
    pe_staging: "git@github.com:puppetlabs/puppetlabs-pe_staging.git"
    puppet_enterprise: "git@github.com:puppetlabs/puppetlabs-puppet_enterprise.git"
    showoff: "git@github.com:puppetlabs/pltraining-showoff.git"
  forge_modules:
    stunnel: "arusso/stunnel"
    firewall: "puppetlabs/firewall"
    chocolatey: "chocolatey/chocolatey"
    graphite: 
      repo: "dwerder/graphite"
      ref: "5.16.1"
    grafana: "dwerder/grafana"
    docker: "garethr/docker"
    wordpress: "hunner/wordpress"
    irc: "jamtur01/irc"
    fileshare: "jordan/fileshare"
    apache: "puppetlabs/apache"
    concat: "puppetlabs/concat"
    git: "puppetlabs/git"
    haproxy: "puppetlabs/haproxy"
    inifile: "puppetlabs/inifile"
    mysql: "puppetlabs/mysql"
    ntp: 
      repo: "puppetlabs/ntp"
      ref: "4.2.0"
    pe_puppetserver_gem: "puppetlabs/pe_puppetserver_gem"
    puppetserver_gem: "puppetlabs/puppetserver_gem"
    stdlib: "puppetlabs/stdlib"
    vcsrepo: "puppetlabs/vcsrepo"
    windows: "puppetlabs/windows"
    epel: "stahnma/epel"
    exports: "zack/exports"
    r10k: "zack/r10k"
    stunnel: "arusso/stunnel"
  symlinks:
    classroom: "#{source_dir}"
